### ISSUE TITLE
Crash while loading world

### ISSUE THREAD

**Issue by AppPhil** [baseball435/TerraLegion#1]
When I start Terraria-Clone and I click on "Load World" the program crashes and it gives me this error:

Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 11
    at com.jmr.terraria.game.io.WorldIO.loadChunk(WorldIO.java:165)
    at com.jmr.terraria.game.io.WorldIO.loadWorld(WorldIO.java:68)
    at com.jmr.terraria.game.world.World.<init>(World.java:57)
    at com.jmr.terraria.game.views.screen.GameScreen.<init>(GameScreen.java:24)
    at com.jmr.terraria.game.views.screen.MainScreen.update(MainScreen.java:35)
    at com.jmr.terraria.PhysicsGame.render(PhysicsGame.java:118)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:207)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)

I'm not sure if loading worlds is already supported. So sorry if it isn't.

**Comment by jmrapp1** [comment]
The world IO is implemented, but I have not ran into this error. In the save file, the blocks are saved by their ID and then retrieved by it. The way that I have it is that the ID is expected to match the index in the array that the block type is saved. Looking back at the code, the reason that this crashes is because that last statement is not true, the ID's don't match the index where the block type is kept. I have changed the code to find the block type by their ID rather than the index in the array. Pull down 8d59daa48815a6d4ef9cf3f197f6bf54ea7f5c14 to receive this update. Thank you for submitting the error!
